/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DostawaRouteImport } from './routes/dostawa'
import { Route as KoszykRouteImport } from './routes/koszyk'
import { Route as PrywatnoscRouteImport } from './routes/prywatnosc'
import { Route as RegulaminRouteImport } from './routes/regulamin'
import { Route as SklepRouteImport } from './routes/sklep'
import { Route as ZamowienieRouteImport } from './routes/zamowienie'
import { Route as ZapachIdRouteImport } from './routes/zapach.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DostawaRoute = DostawaRouteImport.update({
  id: '/dostawa',
  path: '/dostawa',
  getParentRoute: () => rootRouteImport,
} as any)
const KoszykRoute = KoszykRouteImport.update({
  id: '/koszyk',
  path: '/koszyk',
  getParentRoute: () => rootRouteImport,
} as any)
const PrywatnoscRoute = PrywatnoscRouteImport.update({
  id: '/prywatnosc',
  path: '/prywatnosc',
  getParentRoute: () => rootRouteImport,
} as any)
const RegulaminRoute = RegulaminRouteImport.update({
  id: '/regulamin',
  path: '/regulamin',
  getParentRoute: () => rootRouteImport,
} as any)
const SklepRoute = SklepRouteImport.update({
  id: '/sklep',
  path: '/sklep',
  getParentRoute: () => rootRouteImport,
} as any)
const ZamowienieRoute = ZamowienieRouteImport.update({
  id: '/zamowienie',
  path: '/zamowienie',
  getParentRoute: () => rootRouteImport,
} as any)
const ZapachIdRoute = ZapachIdRouteImport.update({
  id: '/zapach/$id',
  path: '/zapach/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dostawa': typeof DostawaRoute
  '/koszyk': typeof KoszykRoute
  '/prywatnosc': typeof PrywatnoscRoute
  '/regulamin': typeof RegulaminRoute
  '/sklep': typeof SklepRoute
  '/zamowienie': typeof ZamowienieRoute
  '/zapach/$id': typeof ZapachIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dostawa': typeof DostawaRoute
  '/koszyk': typeof KoszykRoute
  '/prywatnosc': typeof PrywatnoscRoute
  '/regulamin': typeof RegulaminRoute
  '/sklep': typeof SklepRoute
  '/zamowienie': typeof ZamowienieRoute
  '/zapach/$id': typeof ZapachIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dostawa': typeof DostawaRoute
  '/koszyk': typeof KoszykRoute
  '/prywatnosc': typeof PrywatnoscRoute
  '/regulamin': typeof RegulaminRoute
  '/sklep': typeof SklepRoute
  '/zamowienie': typeof ZamowienieRoute
  '/zapach/$id': typeof ZapachIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dostawa'
    | '/koszyk'
    | '/prywatnosc'
    | '/regulamin'
    | '/sklep'
    | '/zamowienie'
    | '/zapach/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dostawa'
    | '/koszyk'
    | '/prywatnosc'
    | '/regulamin'
    | '/sklep'
    | '/zamowienie'
    | '/zapach/$id'
  id:
    | '__root__'
    | '/'
    | '/dostawa'
    | '/koszyk'
    | '/prywatnosc'
    | '/regulamin'
    | '/sklep'
    | '/zamowienie'
    | '/zapach/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DostawaRoute: typeof DostawaRoute
  KoszykRoute: typeof KoszykRoute
  PrywatnoscRoute: typeof PrywatnoscRoute
  RegulaminRoute: typeof RegulaminRoute
  SklepRoute: typeof SklepRoute
  ZamowienieRoute: typeof ZamowienieRoute
  ZapachIdRoute: typeof ZapachIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dostawa': {
      id: '/dostawa'
      path: '/dostawa'
      fullPath: '/dostawa'
      preLoaderRoute: typeof DostawaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/koszyk': {
      id: '/koszyk'
      path: '/koszyk'
      fullPath: '/koszyk'
      preLoaderRoute: typeof KoszykRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prywatnosc': {
      id: '/prywatnosc'
      path: '/prywatnosc'
      fullPath: '/prywatnosc'
      preLoaderRoute: typeof PrywatnoscRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regulamin': {
      id: '/regulamin'
      path: '/regulamin'
      fullPath: '/regulamin'
      preLoaderRoute: typeof RegulaminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sklep': {
      id: '/sklep'
      path: '/sklep'
      fullPath: '/sklep'
      preLoaderRoute: typeof SklepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zamowienie': {
      id: '/zamowienie'
      path: '/zamowienie'
      fullPath: '/zamowienie'
      preLoaderRoute: typeof ZamowienieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zapach/$id': {
      id: '/zapach/$id'
      path: '/zapach/$id'
      fullPath: '/zapach/$id'
      preLoaderRoute: typeof ZapachIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DostawaRoute: DostawaRoute,
  KoszykRoute: KoszykRoute,
  PrywatnoscRoute: PrywatnoscRoute,
  RegulaminRoute: RegulaminRoute,
  SklepRoute: SklepRoute,
  ZamowienieRoute: ZamowienieRoute,
  ZapachIdRoute: ZapachIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
